endpoints:
  enabled: false
  jmx.enabled: false
  actuator:
    enabled: true
    id: actuator
  configprops.enabled: true
  env.enabled: true
  metrics.enabled: true
  health.enabled: true
  info.enabled: true
